name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Force deployment to DEV"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: PRD
    values:
      - None
      - DEV
  - name: deployDevSlot
    displayName: "Deploy to DEV Staging Slot?"
    type: boolean
    default: false
  - name: qualityGate
    displayName: "Quality Gate parameters"
    type: object
    default:
      enforceQualityGate: false
      warningVariance: 1
      coverageVariance: 1
      coverageType: 'blocks'
      baseBranch: '$(System.PullRequest.TargetBranch)'
      allowWarningVariance: true
      allowCoverageVariance: true

trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'dev'
  paths:
    include:
    - src/Defra.ReMoS.AssuranceService.UI/*
    - test/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: features/update-quality-gate-parameters-jb
    - repository: EEHCAutomation
      name: DEFRA-EEHC/Defra.Trade.EEHC.Automation
      type: git
      ref: dev
  pipelines:
    - pipeline: INFRA
      source: Defra.EEHC.Infra EUCerts UI WebApp
      trigger:
        branches:
          include:
            - '*'
        stages:
          - DEV

variables:
  APIName: Defra.ReMoS.AssuranceService.UI
  UseProductionData: $[ne(variables['environment'], 'dev')]

extends:
  template: /templates/basic-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary }}
    appName: $(APIName)
    appProject: TRS
    appInstanceNumber: $(nc-region-id)29
    buildProjects: 'src\$(APIName)\$(APIName).csproj'
    publishProject: 'src\$(APIName)\$(APIName).csproj'
    publishArguments: '--configuration Release'
    runHealthCheck: false
    setupSlotKeyVaultAccess: true
    deployDevSlot: ${{ parameters.deployDevSlot }}
    appSettingsEnv:
      dev: >-
       -AzureAdB2C:Instance "https://$(b2cTenant2Name).b2clogin.com"
       -AzureAdB2C:SignUpSignInPolicyId "B2C_1A_EUCerts_SUSI"
       -AzureAdB2C:ResetPasswordPolicyId "B2c_1_Reset_std"
       -AzureAdB2C:Domain "$(b2cTenant2Name).onmicrosoft.com"
       -AzureAdB2C:TenantId "$(b2cTenant2Name).onmicrosoft.com"
       -AzureAdB2C:CallbackPath "/signin-oidc"
       -AzureAdB2C:SignedOutCallbackPath "/signout-oidc"
       -ApimSettings:Authority "$(internalAPIMAudience)"
       -AphaContactDetails:Email "exports@apha.gov.uk"
       -AphaContactDetails:Phone "03000 200 301"      
       -SocSettings:Environment "$(environment)"
       -AphaAdminTrusted:ContactEmails "cheryl.day@defra.gov.uk,colin.rogers1@defra.gov.uk,aphadevtst@gmail.com"
    runSonarScan: true
    runVulnerabilityScan: false
    sonarExclusionPaths: 'src/*.Api*/**,src/Defra.Trade.EUCerts.UI.Vue/ClientApp/coverage/**,src/Defra.Trade.EUCerts.UI.Vue/ClientApp/public/**,src/Defra.Trade.EUCerts.UI.Vue/ClientApp/node_modules/**'
    skipBuildTests: true
    qualityGate: ${{ parameters.qualityGate }}